spring.application.name=scribehealth-backend

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/scribehealth

# JWT
jwt.secret=scribehealth_jwt_super_secret_key_2026_do_not_share_xK9mP3qL8nR5wT2v
jwt.expiry-hours=8

# Server
server.port=8080
